/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.impal.view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author BegalPapua
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HalamanAdmin = new javax.swing.JTabbedPane();
        paneltransaksiparkir = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltransaksiparkir = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidparkir = new javax.swing.JTextField();
        btndeleteparkir = new javax.swing.JButton();
        btneditparkir = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtstatusparkir = new javax.swing.JTextField();
        txtkendaraan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtlokasi = new javax.swing.JTextField();
        btnaddparkir = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        transaksipesanlokasi = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtidpesan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtstatuspesanlokasi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btndeletepesan = new javax.swing.JButton();
        btneditpesan = new javax.swing.JButton();
        btnaddpesan = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbltransaksipesanlokasi = new javax.swing.JTable();
        panellokasiparkir = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbllokasiparkir = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btndeletelokasi = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txKodeRuang = new javax.swing.JTextField();
        btneditlokasi = new javax.swing.JButton();
        BtnTambahRuang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtidlokasi = new javax.swing.JTextField();
        txtnamalokasi = new javax.swing.JTextField();
        txtkategori = new javax.swing.JTextField();
        btnaddlokasi = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        dataspotparkir = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        datakamera = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblkamera = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtsektor = new javax.swing.JTextField();
        btneditkamera = new javax.swing.JButton();
        btndeletekamera = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txKodeMatkul = new javax.swing.JTextField();
        txtidkamera = new javax.swing.JTextField();
        btnaddkamera = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Mahasiswa"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        HalamanAdmin.setBackground(new java.awt.Color(204, 204, 204));

        tbltransaksiparkir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbltransaksiparkir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Parkir", "Status", "Kendaraan", "Lokasi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbltransaksiparkir);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("DATA PARKIR");

        jLabel4.setText("ID Parkir");

        btndeleteparkir.setText("DELETE");

        btneditparkir.setText("EDIT");

        jLabel29.setText("Status");

        jLabel30.setText("Kendaraan");

        jLabel12.setText("Lokasi");

        btnaddparkir.setText("ADD");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btneditparkir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btndeleteparkir)
                        .addGap(39, 39, 39)
                        .addComponent(btnaddparkir))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkendaraan)
                                    .addComponent(txtlokasi)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtstatusparkir, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(txtidparkir))
                                .addGap(1, 1, 1)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(129, 129, 129))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtidparkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtstatusparkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtkendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditparkir)
                    .addComponent(btndeleteparkir)
                    .addComponent(btnaddparkir))
                .addContainerGap())
        );

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel24.setText("TRANSAKSI PARKIR");

        javax.swing.GroupLayout paneltransaksiparkirLayout = new javax.swing.GroupLayout(paneltransaksiparkir);
        paneltransaksiparkir.setLayout(paneltransaksiparkirLayout);
        paneltransaksiparkirLayout.setHorizontalGroup(
            paneltransaksiparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltransaksiparkirLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(paneltransaksiparkirLayout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltransaksiparkirLayout.setVerticalGroup(
            paneltransaksiparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltransaksiparkirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel24)
                .addGap(37, 37, 37)
                .addGroup(paneltransaksiparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        HalamanAdmin.addTab("Transaksi Parkir", paneltransaksiparkir);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("ID Pesan");

        jLabel9.setText("Status");

        jLabel11.setText("DATA PESAN LOKASI");

        btndeletepesan.setText("DELETE");

        btneditpesan.setText("EDIT");

        btnaddpesan.setText("ADD");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btneditpesan)
                        .addGap(32, 32, 32)
                        .addComponent(btndeletepesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnaddpesan))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtstatuspesanlokasi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtidpesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(119, 119, 119))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtidpesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtstatuspesanlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeletepesan)
                    .addComponent(btneditpesan)
                    .addComponent(btnaddpesan))
                .addGap(62, 62, 62))
        );

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel25.setText("TRANSAKSI PESAN LOKASI");

        tbltransaksipesanlokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Pesan", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbltransaksipesanlokasi);

        javax.swing.GroupLayout transaksipesanlokasiLayout = new javax.swing.GroupLayout(transaksipesanlokasi);
        transaksipesanlokasi.setLayout(transaksipesanlokasiLayout);
        transaksipesanlokasiLayout.setHorizontalGroup(
            transaksipesanlokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksipesanlokasiLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(transaksipesanlokasiLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaksipesanlokasiLayout.setVerticalGroup(
            transaksipesanlokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksipesanlokasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(transaksipesanlokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        HalamanAdmin.addTab("Transaksi Pesan Lokasi", transaksipesanlokasi);

        tbllokasiparkir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Lokasi", "Nama Lokasi", "Kategori"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbllokasiparkir);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btndeletelokasi.setText("DELETE");

        jLabel15.setText("DATA LOKASI PARKIR");

        txKodeRuang.setEditable(false);
        txKodeRuang.setBackground(new java.awt.Color(255, 255, 255));
        txKodeRuang.setBorder(null);
        txKodeRuang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btneditlokasi.setText("EDIT");
        btneditlokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditlokasiActionPerformed(evt);
            }
        });

        BtnTambahRuang.setText("Add");
        BtnTambahRuang.setActionCommand("");
        BtnTambahRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahRuangActionPerformed(evt);
            }
        });

        jLabel5.setText("Id Lokasi");

        jLabel6.setText("Nama Lokasi");

        jLabel10.setText("Kategori");

        btnaddlokasi.setText("ADD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txKodeRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btneditlokasi)
                                .addGap(41, 41, 41)
                                .addComponent(btndeletelokasi)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(182, 182, 182))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtidlokasi, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(txtnamalokasi))))
                                .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnaddlokasi)))
                .addGap(110, 110, 110)
                .addComponent(BtnTambahRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txKodeRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtidlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamalokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(BtnTambahRuang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditlokasi)
                    .addComponent(btndeletelokasi)
                    .addComponent(btnaddlokasi))
                .addGap(31, 31, 31))
        );

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel26.setText("DATA LOKASI PARKIR");

        javax.swing.GroupLayout panellokasiparkirLayout = new javax.swing.GroupLayout(panellokasiparkir);
        panellokasiparkir.setLayout(panellokasiparkirLayout);
        panellokasiparkirLayout.setHorizontalGroup(
            panellokasiparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellokasiparkirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellokasiparkirLayout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(307, 307, 307))
        );
        panellokasiparkirLayout.setVerticalGroup(
            panellokasiparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellokasiparkirLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(panellokasiparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        HalamanAdmin.addTab("Lokasi Parkir", panellokasiparkir);

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel27.setText("DATA SPOT PARKIR");

        javax.swing.GroupLayout dataspotparkirLayout = new javax.swing.GroupLayout(dataspotparkir);
        dataspotparkir.setLayout(dataspotparkirLayout);
        dataspotparkirLayout.setHorizontalGroup(
            dataspotparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataspotparkirLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel27)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        dataspotparkirLayout.setVerticalGroup(
            dataspotparkirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataspotparkirLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel27)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        HalamanAdmin.addTab("Data Spot Parkir", dataspotparkir);

        tblkamera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Kamera", "Sektor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblkamera);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("INFO DATA KAMERA");

        btneditkamera.setText("EDIT");

        btndeletekamera.setText("DELETE");

        jLabel20.setText("Sektor");

        jLabel19.setText("ID Kamera");

        txKodeMatkul.setEditable(false);
        txKodeMatkul.setBackground(new java.awt.Color(255, 255, 255));
        txKodeMatkul.setBorder(null);

        btnaddkamera.setText("Add");
        btnaddkamera.setActionCommand("");
        btnaddkamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddkameraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtsektor)
                            .addComponent(txtidkamera, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btneditkamera)
                        .addGap(18, 18, 18)
                        .addComponent(btndeletekamera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnaddkamera, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel20))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidkamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtsektor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditkamera)
                    .addComponent(btndeletekamera)
                    .addComponent(btnaddkamera))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel28.setText("DATA KAMERA");

        javax.swing.GroupLayout datakameraLayout = new javax.swing.GroupLayout(datakamera);
        datakamera.setLayout(datakameraLayout);
        datakameraLayout.setHorizontalGroup(
            datakameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datakameraLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(datakameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datakameraLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datakameraLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(293, 293, 293))))
        );
        datakameraLayout.setVerticalGroup(
            datakameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datakameraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(38, 38, 38)
                .addGroup(datakameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        HalamanAdmin.addTab("Data Kamera", datakamera);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN");

        btnlogout.setBackground(new java.awt.Color(204, 204, 255));
        btnlogout.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        btnlogout.setText("LOGOUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(362, 362, 362))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnlogout)
                    .addComponent(HalamanAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HalamanAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnlogout)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddkameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddkameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddkameraActionPerformed

    private void BtnTambahRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahRuangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTambahRuangActionPerformed

    private void btneditlokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditlokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditlokasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public JPanel getMahasiswa() {
        return paneltransaksiparkir;
    }

    public void setPanelTransaksiParkir(JPanel paneltransasiparkir) {
        this.paneltransaksiparkir = paneltransasiparkir;
    }

    public JPanel geTransaksipesanlokasi() {
        return transaksipesanlokasi;
    }

    public void setTransaksipesanlokasi(JPanel transaksipesanlokasi) {
        this.transaksipesanlokasi = transaksipesanlokasi;
    }

    public JPanel getPanellokasiparkir() {
        return panellokasiparkir;
    }

    public void setPanellokasiparkir(JPanel panellokasiparkir) {
        this.panellokasiparkir = panellokasiparkir;
    }

    public JPanel getDatakamera() {
        return datakamera;
    }

    public void setDatakamera(JPanel datakamera) {
        this.datakamera = datakamera;
    }

    public JButton getBtndeleteparkir() {
        return btndeleteparkir;
    }

    public void setBtndeleteparkir(JButton btndeleteparkir) {
        this.btndeleteparkir = btndeleteparkir;
    }




    public JButton getBtneditparkir() {
        return btneditparkir;
    }

    public void setbtneditparkir(JButton btneditparkir) {
        this.btneditparkir = btneditparkir;
    }

    public JButton getBtneditpesan() {
        return btneditpesan;
    }

    public void setBtneditpesan(JButton btneditpesan) {
        this.btneditpesan = btneditpesan;
    }


    public JButton getBtndeletekamera() {
        return btndeletekamera;
    }

    public void setbtndeletekamera(JButton btndeletekamera) {
        this.btndeletekamera = btndeletekamera;
    }

    public JButton getbtndeletelokasi() {
        return btndeletelokasi;
    }

    public void setBtnbtndeletelokasi(JButton btndeletelokasi) {
        this.btndeletelokasi = btndeletelokasi;
    }

    public JButton getbtneditkamera() {
        return btneditkamera;
    }

    public void setbtneditkamera(JButton btneditkamera) {
        this.btneditkamera = btneditkamera;
    }

    public JButton getbtneditlokasi() {
        return btneditlokasi;
    }

    public void setbtneditlokasi(JButton btneditlokasi) {
        this.btneditlokasi = btneditlokasi;
    }

    public JButton btnaddkamera() {
        return btnaddkamera;
    }


    public JTable gettbltransaksiparkir() {
        return tbltransaksiparkir;
    }

    public void settbltransaksiparkir(JTable tbltransaksiparkir) {
        this.tbltransaksiparkir = tbltransaksiparkir;
    }

    

    public String gettxtstatuspesanlokasi() {
        return txtstatuspesanlokasi.getText();
    }

    public void settxtstatuspesanlokasi(String jurusan) {
        this.txtstatuspesanlokasi.setText(jurusan);
    }

    public String gettxtidparkir() {
        return txtidparkir.getText();
    }

    public void settxtidparkir(String idparkir) {
        this.txtidparkir.setText(idparkir);
    }

    public String gettxtidpesan() {
        return txtidpesan.getText();
    }

    public void settxtidpesan(String idpesan) {
        this.txtidpesan.setText(idpesan);
    }


    public JTable getTblKamera() {
        return tblkamera;
    }

    public void setTblKamera(JTable tblKamera) {
        this.tblkamera = tblKamera;
    }

    public JTable getTblLokasiParkir() {
        return tbllokasiparkir;
    }

    public void setTblLokasiParkir(JTable tbllokasiparkir) {
        this.tbllokasiparkir = tbllokasiparkir;
    }

    public String getTxKodeMatkul() {
        return txKodeMatkul.getText();
    }

    public String getTxKodeRuang() {
        return txKodeRuang.getText();
    }

    public void setTxKodeRuang(String kodeRuangan) {
        this.txKodeRuang.setText(kodeRuangan);
    }

    public String gettxtsektor() {
        return txtsektor.getText();
    }

    public void settxtsektorl(String namaSektor) {
        this.txtsektor.setText(namaSektor);
    }

   
    public JButton getBtnLogOut() {
        return btnlogout;
    }

    public void setBtnLogOut(JButton btnLogOut) {
        this.btnlogout = btnLogOut;
    }
    
    public void setActionListener(ActionListener e) {
        btndeleteparkir.addActionListener(e);
        btndeletepesan.addActionListener(e);
        btneditparkir.addActionListener(e);
        btneditpesan.addActionListener(e);
        btnaddkamera.addActionListener(e);
        btndeletekamera.addActionListener(e);
        btndeletelokasi.addActionListener(e);
        btneditkamera.addActionListener(e);
        btneditlokasi.addActionListener(e);
        btnlogout.addActionListener(e);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTambahRuang;
    private javax.swing.JTabbedPane HalamanAdmin;
    private javax.swing.JButton btnaddkamera;
    private javax.swing.JButton btnaddlokasi;
    private javax.swing.JButton btnaddparkir;
    private javax.swing.JButton btnaddpesan;
    private javax.swing.JButton btndeletekamera;
    private javax.swing.JButton btndeletelokasi;
    private javax.swing.JButton btndeleteparkir;
    private javax.swing.JButton btndeletepesan;
    private javax.swing.JButton btneditkamera;
    private javax.swing.JButton btneditlokasi;
    private javax.swing.JButton btneditparkir;
    private javax.swing.JButton btneditpesan;
    private javax.swing.JButton btnlogout;
    private javax.swing.JPanel datakamera;
    private javax.swing.JPanel dataspotparkir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel panellokasiparkir;
    private javax.swing.JPanel paneltransaksiparkir;
    private javax.swing.JTable tblkamera;
    private javax.swing.JTable tbllokasiparkir;
    private javax.swing.JTable tbltransaksiparkir;
    private javax.swing.JTable tbltransaksipesanlokasi;
    private javax.swing.JPanel transaksipesanlokasi;
    private javax.swing.JTextField txKodeMatkul;
    private javax.swing.JTextField txKodeRuang;
    private javax.swing.JTextField txtidkamera;
    private javax.swing.JTextField txtidlokasi;
    private javax.swing.JTextField txtidparkir;
    private javax.swing.JTextField txtidpesan;
    private javax.swing.JTextField txtkategori;
    private javax.swing.JTextField txtkendaraan;
    private javax.swing.JTextField txtlokasi;
    private javax.swing.JTextField txtnamalokasi;
    private javax.swing.JTextField txtsektor;
    private javax.swing.JTextField txtstatusparkir;
    private javax.swing.JTextField txtstatuspesanlokasi;
    // End of variables declaration//GEN-END:variables
}
